### ISSUE TITLE
Dream Yacht 

### ISSUE THREAD

**Issue by Tiff2serious** [DestinationHome/Destination-Home-Online#37] opened 2022-10-31 20:30 UTC
**Describe the bug**
The Dream yacht is stuck on the loading screen. 

**Screenshots & Video Documentation**
![20221031_111031](https://user-images.githubusercontent.com/108475784/199104278-952a6a54-a166-4ad7-979e-57288509ca81.jpg)

# Client Information:
**Region:** North America 
**Country:** US
**Platform:** PS3
**Firmware Type:** HFW,

**Additional context**
Add any other context about the problem here, that you may see fit to give a general overview of this issue.

**Comment by I-Knight-I** [comment] 2022-11-01 23:38
Duplicate of #31

**Closed by I-Knight-I** 2022-11-01 23:38 UTC
Labels: Bug, Duplicate
